export function adminConsoleHtml() {
  return `<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Gateway Console</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:#171717;background:#f5f5f5}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1200px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:20px}.brand{font-size:24px;font-weight:800}.muted{color:#666;font-size:13px}.bar,.card{background:#fff;border:1px solid #e5e5e5;border-radius:14px;padding:16px;box-shadow:0 1px 3px #0000000a}.bar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:16px}input,select,button{font:inherit;border:1px solid #d4d4d4;border-radius:9px;padding:9px 11px;background:#fff}button{cursor:pointer;font-weight:650}button.primary{background:#171717;color:#fff;border-color:#171717}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.metric b{font-size:24px;display:block;margin-top:6px}.two{display:grid;grid-template-columns:2fr 1fr;gap:16px}.card h2{font-size:16px;margin:0 0 12px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #eee}th{color:#666;font-weight:600}.right{text-align:right}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#f1f1f1}.error{color:#b91c1c}.ok{color:#166534}.modal{position:fixed;inset:0;background:#0008;display:none;align-items:center;justify-content:center;padding:20px}.modal.open{display:flex}.modal .box{width:min(520px,100%);background:white;border-radius:16px;padding:20px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.secret{word-break:break-all;background:#f5f5f5;padding:12px;border-radius:10px;font-family:monospace}.hide{display:none}@media(max-width:850px){.grid{grid-template-columns:1fr 1fr}.two{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}@media(max-width:520px){.grid{grid-template-columns:1fr}.row{grid-template-columns:1fr}}
</style></head><body><div class="wrap">
<div class="top"><div><div class="brand">AI Gateway Console</div><div class="muted">多租戶 AI 用量、成本、毛利與計費管理</div></div><div><button id="logout">清除管理金鑰</button></div></div>
<div class="bar"><input id="adminKey" type="password" placeholder="ADMIN_API_KEY" style="min-width:260px"><input id="month" type="month"><button class="primary" id="load">載入 Dashboard</button><button id="newTenant">新增客戶</button><span id="msg" class="muted"></span></div>
<div class="grid"><div class="card metric">本月呼叫<b id="requests">-</b></div><div class="card metric">AI 成本<b id="cost">-</b></div><div class="card metric">應收營收<b id="revenue">-</b></div><div class="card metric">毛利 / 毛利率<b id="profit">-</b></div></div>
<div class="two"><div class="card"><h2>客戶用量</h2><div style="overflow:auto"><table><thead><tr><th>客戶</th><th class="right">呼叫</th><th class="right">圖片</th><th class="right">AI 成本</th><th class="right">應收</th><th class="right">毛利</th><th></th></tr></thead><tbody id="tenants"></tbody></table></div></div>
<div class="card"><h2>帳單</h2><div id="invoices" class="muted">尚未載入</div></div></div>
</div>
<div class="modal" id="tenantModal"><div class="box"><h2>新增客戶</h2><div class="row"><input id="tenantName" placeholder="客戶名稱"><select id="billingMode"><option value="postpaid">月結 postpaid</option><option value="prepaid">預付 prepaid</option><option value="byok">BYOK</option></select></div><div class="row" style="margin-top:10px"><input id="markup" type="number" value="30" min="0" step="1" placeholder="Markup %"><select id="plan"><option value="">不綁方案</option><option value="plan_starter">Starter</option><option value="plan_pro">Pro</option><option value="plan_business">Business</option></select></div><div class="actions"><button data-close="tenantModal">取消</button><button class="primary" id="saveTenant">建立</button></div></div></div>
<div class="modal" id="keyModal"><div class="box"><h2>建立 API Key</h2><input id="keyName" value="default" placeholder="Key 名稱" style="width:100%"><div id="keyResult" class="hide"><p class="muted">此金鑰只顯示一次，請立即保存：</p><div class="secret" id="plainKey"></div></div><div class="actions"><button data-close="keyModal">關閉</button><button class="primary" id="createKey">建立 Key</button></div></div></div>
<script>
const $=s=>document.querySelector(s);const money=n=>'NT$'+Number(n||0).toLocaleString('zh-TW',{maximumFractionDigits:2});
$('#month').value=new Date().toISOString().slice(0,7);$('#adminKey').value=sessionStorage.getItem('agw_admin_key')||'';
function key(){const v=$('#adminKey').value.trim();if(v)sessionStorage.setItem('agw_admin_key',v);return v}async function api(path,opt={}){const h=new Headers(opt.headers||{});h.set('X-Admin-Key',key());if(opt.body)h.set('Content-Type','application/json');const r=await fetch(path,{...opt,headers:h});const b=await r.json();if(!r.ok)throw new Error(b.error||'request_failed');return b}
function msg(t,err=false){$('#msg').textContent=t;$('#msg').className=err?'error':'muted'}
async function load(){try{msg('載入中…');const m=$('#month').value;const [d,iv]=await Promise.all([api('/admin/dashboard?month='+m),api('/admin/invoices')]);const t=d.totals;$('#requests').textContent=Number(t.requests||0).toLocaleString();$('#cost').textContent=money(t.provider_cost_twd);$('#revenue').textContent=money(t.revenue_twd);$('#profit').textContent=money(t.gross_profit_twd)+' / '+Number(t.gross_margin_percent||0).toFixed(1)+'%';$('#tenants').innerHTML=d.tenants.map(x=>`<tr><td><b>${esc(x.name)}</b><div class="muted">${esc(x.id)}</div></td><td class="right">${x.requests||0}</td><td class="right">${x.images||0}</td><td class="right">${money(x.provider_cost_twd)}</td><td class="right">${money(x.revenue_twd)}</td><td class="right">${money(x.gross_profit_twd)}</td><td><button onclick="makeKey('${js(x.id)}')">API Key</button> <button onclick="invoice('${js(x.id)}')">月結</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">尚無客戶資料</td></tr>';$('#invoices').innerHTML=(iv.invoices||[]).slice(0,12).map(x=>`<div style="padding:9px 0;border-bottom:1px solid #eee"><b>${esc(x.tenant_name)}</b><br><span>${money(x.total_twd)} · <span class="pill">${esc(x.status)}</span></span></div>`).join('')||'尚無帳單';msg('已更新')}catch(e){msg(e.message,true)}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function js(s){return String(s).replace(/['\\]/g,'\\$&')}
$('#load').onclick=load;$('#logout').onclick=()=>{sessionStorage.removeItem('agw_admin_key');$('#adminKey').value='';msg('已清除')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('open'));$('#newTenant').onclick=()=>$('#tenantModal').classList.add('open');
$('#saveTenant').onclick=async()=>{try{await api('/admin/tenants',{method:'POST',body:JSON.stringify({name:$('#tenantName').value,billing_mode:$('#billingMode').value,markup_percent:Number($('#markup').value||30),plan_id:$('#plan').value||null})});$('#tenantModal').classList.remove('open');$('#tenantName').value='';await load()}catch(e){alert(e.message)}};
window.makeKey=id=>{$('#keyModal').dataset.tenant=id;$('#keyResult').classList.add('hide');$('#keyModal').classList.add('open')};$('#createKey').onclick=async()=>{try{const r=await api('/admin/tenants/'+encodeURIComponent($('#keyModal').dataset.tenant)+'/keys',{method:'POST',body:JSON.stringify({name:$('#keyName').value||'default'})});$('#plainKey').textContent=r.api_key;$('#keyResult').classList.remove('hide')}catch(e){alert(e.message)}};
window.invoice=async id=>{try{await api('/admin/tenants/'+encodeURIComponent(id)+'/invoices?month='+$('#month').value,{method:'POST'});await load()}catch(e){alert(e.message)}};
if($('#adminKey').value)load();
</script></body></html>`;
}
